#!/bin/bash

SELF=(`realpath $0`)
SELF_DIR=(`dirname $SELF`)
pkill -f 'kanban-web-server'
xdg-open http://localhost:9898 > /dev/null 2>&1 &
echo "Starting PHP server in $SELF_DIR. Press Ctrl+C to stop."
WORK_DIR=`pwd` php -d variables_order=EGPCS -d kanban-web-server=true -S localhost:9898 $SELF_DIR/index.php > /dev/null 2>&1
